### ISSUE TITLE
Support for multiple hubs?

### ISSUE THREAD

**Issue by divnull** [nsheldon/Hue-Lights-Indigo-plugin#2]
I have two HUE hubs in my network. As far as I can tell, this plugin supports only one at a time. Is this true? Or is there some workaround? What would it take to support multiple hubs?

**Comment by nsheldon** [comment]
Correct.  The Hue Lights plugin only supports 1 hub.  I believe the newest Hue hub model that works with Apple HomeKit supports at least 100 devices (compared to the limit of 50 for the last hub).  However, if you need to control multiple hubs, there is a workaround for the Hue Lights plugin.  See [this](http://forums.indigodomo.com/viewtopic.php?f=31&t=13304&hilit=hue+multiple+hub) Indigo Domotics forum post for instructions on how to do this.

**Comment by nsheldon** [comment]
Feature added in version 1.8.0
